## Датасет собран из базы данных переписи 1994 года и содержит данные о доходах.
### Информация о данных:
* age: continuous.
* workclass: Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, Never-worked.
* fnlwgt: continuous.
* education: Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc, 9th, 7th-8th, 12th, * Masters, 1st-4th, 10th, Doctorate, 5th-6th, Preschool.
* education-num: continuous.
* marital-status: Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, Married-AF-spouse.
* occupation: Tech-support, Craft-repair, Other-service, Sales, Exec-managerial, Prof-specialty, Handlers-cleaners, Machine-op-inspct, Adm-clerical, Farming-fishing, Transport-moving, Priv-house-serv, Protective-serv, Armed-Forces.
* relationship: Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried.
* race: White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black.
* sex: Female, Male.
* capital-gain: continuous.
* capital-loss: continuous.
* hours-per-week: continuous.
* native-country: United-States, Cambodia, England, Puerto-Rico, Canada, Germany, Outlying-US(Guam-USVI-etc), India, Japan, Greece, South, China, Cuba, Iran, Honduras, Philippines, Italy, Poland, Jamaica, Vietnam, Mexico, Portugal, Ireland, France, Dominican-Republic, Laos, Ecuador, Taiwan, Haiti, Columbia, Hungary, Guatemala, Nicaragua, Scotland, Thailand, Yugoslavia, El-Salvador, Trinadad&Tobago, Peru, Hong, Holand-Netherlands.
* salary: >50K,<=50K

## Проведите анализ данных при помощи Pandas выполнив поставленные задачи.
####

In [86]:
import pandas as pd
from numpy.ma.extras import unique

In [87]:
# загружаем датасет
data = pd.read_csv("./data/adult.data.csv")
data.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

**1. Посчитайте, сколько мужчин и женщин (признак *sex*) представлено в этом датасете**

In [88]:
print(data['sex'].value_counts())

sex
Male      21790
Female    10771
Name: count, dtype: int64

**2. Каков средний возраст мужчин (признак *age*) по всему датасету?**

In [89]:
data_m = data[data['sex'] == 'Male']
res = data_m['age'].mean()
print(res)

39.43354749885268

**3. Какова доля граждан Соединенных Штатов (признак *native-country*)?**

In [90]:
everybody = len(data)
usa_natives = len(data[data['native-country'] == 'United-States'])
print(usa_natives/everybody)

0.895857006848684

**4-5. Рассчитайте среднее значение и среднеквадратичное отклонение возраста тех, кто получает более 50K в год (признак *salary*) и тех, кто получает менее 50K в год**

In [91]:
print(data.groupby('salary')['age'].mean())
print(data.groupby('salary')['age'].std())

salary
<=50K    36.783738
>50K     44.249841
Name: age, dtype: float64
salary
<=50K    14.020088
>50K     10.519028
Name: age, dtype: float64

**6. Правда ли, что люди, которые получают больше 50k, имеют минимум высшее образование? (признак *education – Bachelors, Prof-school, Assoc-acdm, Assoc-voc, Masters* или *Doctorate*)**

In [92]:
import numpy as np
education = ['Bachelors', 'Prof-school', 'Assoc-acdm', 'Assoc-voc', 'Masters', 'Doctorate']
educated = data['education'].isin(education) # educated - true, not educated - false
high_salary = educated[data['salary'] == '>50K'] # only high salary
print(high_salary.all()) # all high salary - educated

False

**7. Выведите статистику возраста для каждой расы (признак *race*) и каждого пола. Используйте *groupby* и *describe*. Найдите таким образом максимальный возраст мужчин расы *Asian-Pac-Islander*.**

In [93]:
data.groupby(['race', 'sex'])['age'].describe()

                             count       mean        std   min   25%   50%  \
race               sex
Amer-Indian-Eskimo Female    119.0  37.117647  13.114991  17.0  27.0  36.0
                   Male      192.0  37.208333  12.049563  17.0  28.0  35.0
Asian-Pac-Islander Female    346.0  35.089595  12.300845  17.0  25.0  33.0
                   Male      693.0  39.073593  12.883944  18.0  29.0  37.0
Black              Female   1555.0  37.854019  12.637197  17.0  28.0  37.0
                   Male     1569.0  37.682600  12.882612  17.0  27.0  36.0
Other              Female    109.0  31.678899  11.631599  17.0  23.0  29.0
                   Male      162.0  34.654321  11.355531  17.0  26.0  32.0
White              Female   8642.0  36.811618  14.329093  17.0  25.0  35.0
                   Male    19174.0  39.652498  13.436029  17.0  29.0  38.0

                             75%   max
race               sex
Amer-Indian-Eskimo Female  46.00  80.0
                   Male    45.00  82.0
Asian-Pac-Islander Female  43.75  75.0
                   Male    46.00  90.0
Black              Female  46.00  90.0
                   Male    46.00  90.0
Other              Female  39.00  74.0
                   Male    42.00  77.0
White              Female  46.00  90.0
                   Male    49.00  90.0

**8. Среди кого больше доля зарабатывающих много (>50K): среди женатых или холостых мужчин (признак *marital-status*)? Женатыми считаем тех, у кого *marital-status* начинается с *Married* (Married-civ-spouse, Married-spouse-absent или Married-AF-spouse), остальных считаем холостыми.**

In [94]:
res_for_married = data[(data['sex'] == 'Male') & data['marital-status'].str.startswith('Married')]['salary'].eq('>50K').mean()*100
res_for_single = data[(data['sex'] == 'Male') & ~(data['marital-status'].str.startswith('Married'))]['salary'].eq('>50K').mean()*100
print(res_for_married)
print(res_for_single)
res = 'married' if res_for_married > res_for_single else 'single'
print(res)

44.05139945351156
8.449509031397746
married

**9. Какое максимальное число часов человек работает в неделю (признак *hours-per-week*)? Сколько людей работают такое количество часов и каков среди них процент зарабатывающих много?**

In [95]:
max_hours_per_week = data['hours-per-week'].max()
print(f'max hours per week - {max_hours_per_week}')
hard_workers = data[data['hours-per-week'] == max_hours_per_week]
print(f'number of people working max hours per week - {len(hard_workers)}')
res = hard_workers['salary'].eq('>50K').mean()*100
print(f'{res}% of hard workers have high salary')

max hours per week - 99
number of people working max hours per week - 85
29.411764705882355% of hard workers have high salary

**10. Посчитайте среднее время работы (*hours-per-week*) зарабатывающих мало и много (*salary*) для каждой страны (*native-country*).**

In [96]:
grouped = data.groupby(['salary', 'native-country'])['hours-per-week'].mean()
print(grouped)

salary  native-country
<=50K   ?                  40.164760
        Cambodia           41.416667
        Canada             37.914634
        China              37.381818
        Columbia           38.684211
                             ...
>50K    Thailand           58.333333
        Trinadad&Tobago    40.000000
        United-States      45.505369
        Vietnam            39.200000
        Yugoslavia         49.500000
Name: hours-per-week, Length: 82, dtype: float64

**11.Сгруппируйте людей по возрастным группам *young*, *adult*, *retiree*, где:**
* *young* соответствует 16-35 лет
* *adult* - 35-70 лет
* *retiree* - 70-100 лет

**Проставьте название соответсвтуещей группы для каждого человека в новой колонке AgeGroup**

In [97]:
import numpy as np
cond = [
    (data['age'] >= 16) & (data['age'] <= 35),
    (data['age'] > 35) & (data['age'] <= 70),
    (data['age'] > 70) & (data['age'] <= 100)
]
lable = ['young', 'adult', 'retiree']
data['AgeGroup'] = np.select(cond, lable, default='Неизвестно')
print(data['AgeGroup'])

0        adult
1        adult
2        adult
3        adult
4        young
         ...
32556    young
32557    adult
32558    adult
32559    young
32560    adult
Name: AgeGroup, Length: 32561, dtype: object

**12-13. Определите количество зарабатывающих >50K в каждой из возрастных групп (колонка AgeGroup), а также выведите название возрастной группы, в которой чаще зарабатывают больше 50К (>50K)**

In [98]:
data['higher_sal'] = data['salary'] == '>50K'
grouped = data.groupby('AgeGroup')['higher_sal'].mean() * 100
print(grouped)
res = grouped[grouped == grouped.max()].index[0]
print(f'{res} - more percent of high salary')

AgeGroup
adult      35.341600
retiree    17.407407
young      11.423786
Name: higher_sal, dtype: float64
adult - more percent of high salary

**14. Сгруппируйте людей по типу занятости (колонка occupation) и определите количество людей в каждой группе. После чего напишите функциюю фильтрации filter_func, которая будет возвращать только те группы, в которых средний возраст (колонка age) не больше 40 и в которых все работники отрабатывают более 5 часов в неделю (колонка hours-per-week)**

In [109]:
data_f = data.groupby('occupation').size()
print(f'count of people for every group - {data_f}')
def filter_func(mydata):
    age_condition = mydata['age'].mean() <= 40
    hours_condition = (mydata['hours-per-week'] > 5).all()
    return age_condition and hours_condition
res = data.groupby('occupation').filter(filter_func)
print(f' group - {res['occupation'].unique()[0]}')

count of people for every group - occupation
?                    1843
Adm-clerical         3770
Armed-Forces            9
Craft-repair         4099
Exec-managerial      4066
Farming-fishing       994
Handlers-cleaners    1370
Machine-op-inspct    2002
Other-service        3295
Priv-house-serv       149
Prof-specialty       4140
Protective-serv       649
Sales                3650
Tech-support          928
Transport-moving     1597
dtype: int64
 group - Armed-Forces